name: "$name"
version: "$version"
main: kz.hxncus.mc.minesonapi.MinesonAPI
api-version: '1.13'
depend:
  - ProtocolLib
softdepend:
  - FastAsyncWorldEdit
  - WorldGuard
commands:
  basic:
    description: Hello, this is basic command
    aliases:
      - basis
      - test